### ISSUE TITLE
App got rejected from playstore 

### ISSUE THREAD

**Issue by pralgomathic** [PierfrancescoSoffritti/Android-YouTube-Player#82] opened 2018-01-15 19:56 UTC
"Your app shouldn’t access or use a service or API in a manner that violates its terms of service. For example, make sure your app doesn’t download, monetize, or access YouTube videos in a way that violates the YouTube Terms of Service.
Read through the Device and Network Abuse policy for more details and examples.
Make sure your app is compliant with all other policies listed in the Developer Program Policies. Remember that additional enforcement could occur if there are further policy issues with your apps.
Sign in to your Developer Console and submit your app."

**Comment by PierfrancescoSoffritti** [comment] 2018-01-15 20:21
duplicate of #70

**Closed by PierfrancescoSoffritti** 2018-01-15 20:21 UTC
