### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by looploooop** [PierfrancescoSoffritti/android-youtube-player#199] opened 2018-09-05 08:01 UTC
Closing a fragment with youTubePlayerView and calling release() or respectively add the view as a lifecycle observer will lead to an infinite loading when opening the fragment quickly again.

Waiting for a couple of seconds between opening the fragment again and youTubePlayerView initialize will work correctly. Though often neither onReady or onError are called when the time between opening and closing the fragment is roughly between 1-3 seconds.

Infinite loading does not happen when release is not called.

**Comment by PierfrancescoSoffritti** [comment] 2018-09-05 08:08
Interesting, is this happening only with Fragments? I have not been able to reproduce it with Activities. (And currently don't have any Fragment to test it)

**Comment by looploooop** [comment] 2018-09-05 08:50
I have only tested this with fragments so far.

**Comment by looploooop** [comment] 2018-09-29 10:53
[These](https://stackoverflow.com/questions/17418503/destroy-webview-in-android?answertab=votes#tab-top) suggestions on stackoverflow for cleaning up resources of webview solved the problem for me.

**Comment by PierfrancescoSoffritti** [comment] 2018-09-29 11:03
Thanks for the link! I will be back home in a couple of weeks, then I'll investigate the issue and let you know. Sorry for the delay.

**Comment by yuxiaohui78** [comment] 2018-10-11 19:01
I have this issue too on Activity.
I have a video list. When I click an item in the list, I will open the youtubeplayer to play the video.
When I quickly click the list item and exit the youtubeplayer, just 3 to 5 times, the youtubeplayer will be infinite loading state.

**Comment by PierfrancescoSoffritti** [comment] 2018-10-12 05:20
Interesting, thanks for the reporting the issue.
I have been very busy lately and hadn't had time to look into it yet, this extra info will be useful when I will.

**Comment by aman01894** [comment] 2018-11-03 09:38
I have also infinite loading issue,
When i am cast video in device  new fragment open and show loading infinite.
please help me.

**Comment by PierfrancescoSoffritti** [comment] 2018-11-03 10:02
@aman01894 does the video every play? if it never plays most likely you haven't initialized the player properly.

**Comment by aman01894** [comment] 2018-11-03 10:09
Video only play when I am not using chrome cast. But when I try to play using chrome cast it shows me loader for infinite state.

**Comment by PierfrancescoSoffritti** [comment] 2018-11-03 10:19
Then your problem is not related to this issue. Please open a new one.

**Comment by PierfrancescoSoffritti** [comment] 2018-11-10 10:01
I have added a Fragment example to the sample app, but I'm not able to reproduce the issue with it. Even after opening-closing-opening in less than 1 second.

**Closed by PierfrancescoSoffritti** 2018-11-10 10:01 UTC
Labels: bug
