### ISSUE TITLE
Is there any method to check if player is already initialized?

### ISSUE THREAD

**Issue by BhagyashreeWani** [PierfrancescoSoffritti/android-youtube-player#833] opened 2022-04-04 17:40 UTC
Is there any method to check if player is already initialized? 
Or
I am getting below error (Screenshot attached) in youtubePlayerview. Same videoId is working with https://www.youtube.com/

![youtubePLayerSS](https://user-images.githubusercontent.com/19743601/161398066-a3a39e1e-907b-4cb7-9127-0fbd16303d6d.png)

After getting such error for first video, I am unable to play next videoId in same youtubePlayerView and getting error as - java.lang.IllegalStateException: This YouTubePlayerView has already been initialized.

I am using -
Kotlin
view binding 
reference from xml - binding.youtubePlayerView

_Originally posted by @BhagyashreeWani in https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/832#issuecomment-1086702380_

**Comment by PierfrancescoSoffritti** [comment] 2022-04-04 18:38
I suggest you take a look at the examples in the sample app. A YouTubePlayer is initialized from the moment you get it.

**Comment by Devenom1** [comment] 2023-05-20 15:16
I have the same issue. I used it in a recyclerview. And it gives this error starting from the 3rd position usually. I initialized the ytplay view using the initialize method.

**Comment by PierfrancescoSoffritti** [comment] 2023-05-20 15:45
Have you looked at the sample app? it works there.

**Comment by Devenom1** [comment] 2023-05-20 16:43
Hey @PierfrancescoSoffritti thanks for replying so soon. Yes I did but I also kept the code to enable a fullscreen view (which is not in the recyclerview example). This requires us to manually call the initialize method (if I'm not mistaken). It gives an error on that line.

I don't think this is helpful but just in case it is this is what I do. I have an activity with a fragment in it. The recycler view is in the fragment. The recycler view has access to the fullscreen `FrameLayout` of the activity because I paased a reference to it.

**Comment by Devenom1** [comment] 2023-05-20 17:19
So this is what is happening in my case. I use a RecyclerView because I have multiple videos. I also require to use the full screen functionality on each video. So I add this code like this
```
youtubePlayerView.enableAutomaticInitialization = false

val iFramePlayerOptions = IFramePlayerOptions.Builder()
    .controls(1)
    .fullscreen(1) // enable full screen button
    .build()

youtubePlayerView.addFullscreenListener(object : FullscreenListener {
    override fun onEnterFullscreen(fullscreenView: View, exitFullscreen: () -> Unit) {
        isFullscreen = true
       .....
    }

    override fun onExitFullscreen() {
        isFullscreen = false
       .....
    }
})

youtubePlayerView.initialize(object : AbstractYouTubePlayerListener() {
    override fun onReady(youTubePlayer: YouTubePlayer) {
        youTubePlayer.cueVideo(video.youtubeVideoId, 0f)
        ......
    }
}, iFramePlayerOptions)
```

For the fullscreen functionality we need the initialize method (correct me if I am wrong). So here's whats happening in the recyclerview adapter. Since the cells/item views get recycled the view containing the youtube player view also gets recycled. And because of that one of the youtube player view that was already initialized before calls the initialize method again.

I've very new to this library. I love it though. There's at least one good youtube library that supports youtube videos. Please correct me if I'm doing something wrong. Or let me know if there is a work around.

I've implemented a work around but it's not a good one and affects performance.

**Comment by PierfrancescoSoffritti** [comment] 2023-05-21 17:25
What error exactly are you getting? I don't think the issue is the same as described in the original message for this issue? I am going to close this issue, please open a new one for your problem so we can discuss there. Share all the information you have: what problem you're encountering, what your code looks like, what version of the library are you using, etc.

**Closed by PierfrancescoSoffritti** 2023-05-21 17:25 UTC
Labels: question
