### ISSUE TITLE
Android TV Green Screen

### ISSUE THREAD

**Issue by sky286753213** [PierfrancescoSoffritti/android-youtube-player#351] opened 2019-04-16 10:01 UTC
When I use it on Android TV, it will be green when playing video.
![IMG20190416175904](https://user-images.githubusercontent.com/3223923/56200498-83c7ef80-6071-11e9-916f-a5c9f5f33a78.jpg)
![IMG20190416175908](https://user-images.githubusercontent.com/3223923/56200527-8fb3b180-6071-11e9-80b7-d0db79935865.jpg)

**Comment by PierfrancescoSoffritti** [comment] 2019-04-16 12:34
It is probably a problem with the version of webview used on the tv.

**Comment by sky286753213** [comment] 2019-04-16 15:04
> It is probably a problem with the version of webview used on the tv.

Is this caused by hardware acceleration?

**Comment by PierfrancescoSoffritti** [comment] 2019-04-16 15:06
mm possibly, I have no idea to be honest. Do you have it enable?

I have never used the player on Android TV, but other users have, it was working fine for them.

**Comment by sky286753213** [comment] 2019-04-16 15:12
I am trying it, thank you.

**Comment by PierfrancescoSoffritti** [comment] 2019-04-16 15:17
Ok. Let me know if you make any progress!

**Comment by sergiambel** [comment] 2019-05-10 16:26
do we have any progress related with this issue?

**Comment by sergiambel** [comment] 2019-05-10 19:08
I've tested directly with a webview and same problem.

When I defined a small vide size it plays perfect (ie 300dp x 200dp) bute, bigger (400dp x 300dp) or fullscreen back the problem.

**Comment by PierfrancescoSoffritti** [comment] 2019-05-10 23:01
Interesting. Maybe it's worth opening a bug on the IFrame Player issue tracker. I'll look for it tomorrow!

**Comment by sergiambel** [comment] 2019-05-11 07:12
Checking the @sky286753213 photos I've seen the issue is happening in Xiaomi MIBOX4 devices. (We're testing in the same model)

**Comment by sergiambel** [comment] 2019-05-14 15:47
Until Youtube, Android o whatever they want fix this render issue we decided use the Pierfrancesco's library for all users less the Android TV ones.  For them we use this code:

```
Intent intent = YouTubeIntents.createPlayVideoIntentWithOptions(this, videoId, true, true);
startActivity(intent);
```

You'll need add that library to your project:
[https://developers.google.com/youtube/android/player/downloads/](https://developers.google.com/youtube/android/player/downloads/)

More info:
[https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubeIntents](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubeIntents)

**Comment by PierfrancescoSoffritti** [comment] 2019-05-14 20:28
Great, thanks for the update! Could you file a bug here too? So they can look into it. Also after filing the bug could you post the link here?

thanks a lot!

**Comment by sergiambel** [comment] 2019-05-15 10:16
You can install this app in a a Xiaomi MIBOX4 and you'll watch the video in green :).

https://www.dropbox.com/s/xecuca4t04us47p/app-oldmovies-release.apk?dl=0

**Comment by PierfrancescoSoffritti** [comment] 2019-05-15 10:19
Sorry i forgot to attach the link yesterday, too much multitasking lol I have edited the previous comment now.

**Comment by sergiambel** [comment] 2019-05-16 13:21
Reported: https://issuetracker.google.com/issues/132834993

**Comment by PierfrancescoSoffritti** [comment] 2019-05-16 13:28
Thanks!

**Comment by asitjain** [comment] 2019-08-13 04:19
Any update on issue? I am facing the same on Chinese TV Box runin 7.1.1.

**Comment by sergiambel** [comment] 2019-08-13 07:38
Few days ago one user sent me this screenshot taken from a Xiamoi MIBOX4:
![MIBOX4 Last Update](https://user-images.githubusercontent.com/466578/62923435-fcd01d00-bdad-11e9-9177-71179bd7bf11.jpeg)

The problem looks be a hardware/firmware issue and it's fixed in last updates.

**Closed** 2019-08-25 15:35 UTC
Labels: question

**Comment by NIKUNJGAJERA46** [comment] 2020-03-21 03:50
I found the Solution for it.  It's because of Hardware Acceleration ... Can be solved by following line

youTubePlayerView.setLayerType(View.LAYER_TYPE_HARDWARE, null);
