### ISSUE TITLE
Playback quality

### ISSUE THREAD

**Issue by SystemRestored** [PierfrancescoSoffritti/android-youtube-player#372] opened 2019-05-20 03:53 UTC
Can you implement a playback quality settings for the player? original youtube demo player provided by google has the playback quality settings. I am using your player its not shifting to top quality rather always play 480p  if the video has 1080p, or any settings in your code to use the topmost quality from youtube?

**Comment by PierfrancescoSoffritti** [comment] 2019-05-20 10:09
Duplicate of #27.

**Closed by PierfrancescoSoffritti** 2019-05-20 10:09 UTC
Labels: question
