### ISSUE TITLE
Youtube videos not playing in the emulator

### ISSUE THREAD

**Issue by mohanvthink** [PierfrancescoSoffritti/android-youtube-player#327] opened 2019-03-21 14:24 UTC
Videos are playing in the real devices, but it is not playing in the emulator. It just show the half white screen with video timer
![Screenshot_1553178179](https://user-images.githubusercontent.com/13622163/54758967-2fb52100-4c13-11e9-917f-e62a68827442.png)

**Comment by PierfrancescoSoffritti** [comment] 2019-03-22 22:13
Duplicate of issue #112.
I suggest using an emulator running API 28, it should work. Also remember to enable hardware acceleration in your manifest. Check sample app for an example.

**Closed by PierfrancescoSoffritti** 2019-03-22 22:13 UTC
