### ISSUE TITLE
Can we change the thumbnail of video to show at the beginning / pause of video

### ISSUE THREAD

**Issue by nguyenhuutinh** [PierfrancescoSoffritti/android-youtube-player#265] opened 2018-11-28 03:04 UTC
Hi,

Can we change the thumbnail of video to show at the beginning / pause of video.
Because it show Youtube logo and AddHistory/share icon when pause video or loading video.
Thanks

**Comment by PierfrancescoSoffritti** [comment] 2018-11-28 07:11
Hi, this issue is a duplicate of #242. Unfortunately no, it's not possible. YouTube changed things in their player and now there is not way to remove them.

**Closed by PierfrancescoSoffritti** 2018-11-28 07:11 UTC
Labels: question
