### ISSUE TITLE
Video does not load sometimes 

### ISSUE THREAD

**Issue by Archifer** [PierfrancescoSoffritti/android-youtube-player#545] opened 2020-04-03 12:10 UTC
Hi,

In my application, I need to load youtube videos repeatedly on different fragments, but I am encountering an issue where videos will not load sometimes (it keeps showing the loading screen and will not enter the onReady or onError state).

I noticed that every time this error occurred I get the following error:
E/chromium: [ERROR:tile_manager.cc(776)] WARNING: tile memory limits exceeded, some content may not draw

If anyone has any idea on how to fix this I would really appreciate it.

Thanks in advance

**Comment by iuliastanica** [comment] 2020-04-09 19:26
Hello, 

I used to have the same problem all the time. I have sort of a news feed with info of different types, so I (partially) solved it by implementing a recycler view with pagination. 

I observed that this error occured everytime when my video was "hidden" by something, for instance if it was not yet in focus in the recycler view (not yet reached through scrolling). Now I only get the error once in a while, and when I get it, the videos tend to load slower or (rarely) not load at all. 

I don't know exactly if that is the cause and I will love to get the definitive solution to it.

**Comment by luqman456** [comment] 2020-07-24 06:22
i facing same problem in recyleView some time video load but some time it not load even when I click to play video it not through any exception and error

**Comment by app-arianamini** [comment] 2020-08-14 09:02
Same problem here, I think this framework sucks

**Comment by crearo** [comment] 2020-09-21 22:51
Same problem :|

**Comment by adiazarya100** [comment] 2021-04-20 11:05
Same problem :| 
Any news about this bug?

**Comment by dev-lester94** [comment] 2021-07-25 05:50
Anyone have an update on this?

**Comment by PierfrancescoSoffritti** [comment] 2022-07-15 14:37
You do need hardware acceleration. 

This issue seems related to issue #830. Is it possible? if yes i'd like to redirect the conversation there.

**Comment by flauschtrud** [comment] 2022-07-18 07:53
It's hard to tell which of the symptoms in the logs actually relate to my specific problem, but I wanted to mention hardware acceleration here because it definitely fixed the "tile memory limits exceeded" error that the original poster mentioned.
But yes, I guess this issue here can be closed.

**Comment by PierfrancescoSoffritti** [comment] 2022-08-06 04:26
This should be fixed in version 11.1.0.

**Closed by PierfrancescoSoffritti** 2022-08-06 04:26 UTC
