### ISSUE TITLE
Video Quality

### ISSUE THREAD

**Issue by rahulsain-ingeniumedu** [PierfrancescoSoffritti/android-youtube-player#796] opened 2021-12-04 06:50 UTC
Is multiple video quality for YT videos can be implemented?

if not, is there any library that has this feature?

if not then what is the round about solution?

**Comment by PierfrancescoSoffritti** [comment] 2021-12-04 20:47
Duplicate of issue #27

**Closed by PierfrancescoSoffritti** 2021-12-04 20:47 UTC
