### ISSUE TITLE
How to change video quality and playback rate?

### ISSUE THREAD

**Issue by sajithlaldev** [PierfrancescoSoffritti/android-youtube-player#649] opened 2020-10-14 13:48 UTC
How to change video quality and playback rate?

**Comment by elmundomusical4** [comment] 2021-01-24 15:23
Yes please! How can we do it??

**Comment by rahulsain-ingeniumedu** [comment] 2021-12-02 13:22
@PierfrancescoSoffritti is this feature can be implemented?

**Comment by PierfrancescoSoffritti** [comment] 2021-12-04 20:48
Duplicate of issue #27

**Closed by PierfrancescoSoffritti** 2021-12-04 20:48 UTC
