### ISSUE TITLE
taking too much to load video is there any way to get it fast

### ISSUE THREAD

**Issue by sai7779** [PierfrancescoSoffritti/android-youtube-player#867] opened 2022-07-21 11:03 UTC
In my application it is too late to get play the video black screen is coming for appr 30 sec can we reduce this ?do you have any upadates about this @PierfrancescoSoffritti kindly help me its kind of urgent ?     edit : any update?

**Comment by tanishq14developer** [comment] 2022-07-30 21:35
yes same issue

**Comment by sai7779** [comment] 2022-08-09 04:59
> yes same issue

have you got any solution?

**Comment by tanishq14developer** [comment] 2022-08-09 05:49
Noo

**Comment by spapapan** [comment] 2022-08-18 11:32
I have this issue sometimes also. Sometimes it doesn't even load the video at all. 

If I had to guess, I would say that there is another instance of the player loaded in a background thread that that causes a conflict.

**Comment by PierfrancescoSoffritti** [comment] 2022-08-18 13:14
> Sometimes it doesn't even load the video at all.

I suggest you update to version 11.1.0. As this is fixed there.

**Comment by PierfrancescoSoffritti** [comment] 2022-08-18 13:15
As per download speed, there's not much I can say with so little information. I never had this problem.

**Comment by spapapan** [comment] 2022-08-18 13:17
I just updated the version to 11.1.0 and I can confirm that the problem is fixed. 
Thanks again for your hard work on this library, you are the best.

**Comment by PierfrancescoSoffritti** [comment] 2022-08-18 13:21
Glad it works for you :)

Closing this issue for now, as there's not much i can do about it.

**Closed by PierfrancescoSoffritti** 2022-08-18 13:21 UTC
