### ISSUE TITLE
Adjust video quality button is not present in Native UI

### ISSUE THREAD

**Issue by piyush1726** [PierfrancescoSoffritti/android-youtube-player#626] opened 2020-09-10 10:31 UTC
How to enable the adjust video quality button in Native UI, like we get in youtube ?

**Comment by hieu-digitoy-xyz** [comment] 2021-01-20 09:19
You can not.

**Comment by PierfrancescoSoffritti** [comment] 2021-12-04 20:48
Duplicate of issue #27

**Closed by PierfrancescoSoffritti** 2021-12-04 20:48 UTC
