### ISSUE TITLE
Change quality Video

### ISSUE THREAD

**Issue by long06031999** [PierfrancescoSoffritti/android-youtube-player#759] opened 2021-07-18 20:59 UTC
How can i change quality video ?

**Comment by HashimAli09** [comment] 2021-11-04 07:59
Any leads on this? can we even change quality?

**Comment by long06031999** [comment] 2021-11-14 13:16
I don't have any solution with this issue.

**Comment by PierfrancescoSoffritti** [comment] 2021-12-04 20:47
Duplicate of issue #27

**Closed by PierfrancescoSoffritti** 2021-12-04 20:47 UTC
