### ISSUE TITLE
Player not running on Mobile data

### ISSUE THREAD

**Issue by mahbub-rahman** [PierfrancescoSoffritti/android-youtube-player#470] opened 2019-11-05 12:27 UTC
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
                android:id="@+id/youtube_view"
                android:layout_width="match_parent"
                android:layout_height="@dimen/size_200dp"
                android:background="@android:color/black"
                app:measureBasedOnAspectRatio="true"
                app:useDefaultControls="false"
                app:videoScale="center"
                />

Player working fine on wifi but not working on mobile data. 
 Error: Please click here to watch this video on youtube

**Comment by Shaheer37** [comment] 2019-11-06 12:00
I am facing the same issue. The player is throwing this error "VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER". when on mobile data but is working on Wifi.

**Comment by PierfrancescoSoffritti** [comment] 2019-11-07 08:57
This is most likely not an issue with the library but with YouTube's embedded web player.

**Comment by joseAugustoCR** [comment] 2019-11-07 20:46
I'm getting this error too VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER, but it doesn't seem related to mobile data or at least doesn't always happen.

**Comment by PierfrancescoSoffritti** [comment] 2019-11-08 13:42
This may be a duplicate of #202.

**Closed** 2019-11-11 09:00 UTC
Labels: question

**Comment by Shaheer37** [comment] 2019-11-18 06:47
@PierfrancescoSoffritti You are right the problem is not with the library but with Youtube iFrame API. But, this is not related to #202
and in my case, it is explicitly and consistently happening on mobile data, as the same video is streaming fine on Broadband.
