### ISSUE TITLE
Violation of Device and Network Abuse policy 

### ISSUE THREAD

**Issue by dileep-n** [PierfrancescoSoffritti/android-youtube-player#192] opened 2018-08-29 04:55 UTC
When using this library, the app is rejected by google playstore. The Reason is app shouldn't download, monetize, or access YouTube videos in a way that violates the YouTube Terms of Service. So is there any solution for this issue?

**Comment by PierfrancescoSoffritti** [comment] 2018-08-29 05:07
Your app is not being rejected because of the library. You are probably violating the terms of services in some other way, for example by showing ads in the wrong way.

**Comment by PierfrancescoSoffritti** [comment] 2018-08-29 05:08
Duplicate of #82.

**Closed** 2018-09-02 08:48 UTC
Labels: question
